### ISSUE TITLE
Focus points flickering seen on different devices

### ISSUE THREAD

**Issue by kounistou** [RafaelBarbosatec/tutorial_coach_mark#230]
Hi,

I'd like to report an issue with flickering in the focus points observed so far on two different devices. I have attached a link to a video below.

This can be seen with both  shape types:
```
shape: ShapeLightFocus.Circle
 
shape: ShapeLightFocus.RRect
```

Here is an example snippet of one of my TargetFocus points if that helps:

```
      TargetFocus(
        identify: "card",
        keyTarget: cardKey,
        enableOverlayTab: true,
        shape: ShapeLightFocus.RRect,
        radius: 24,
        contents: [
          TargetContent(
            align: ContentAlign.bottom,
            builder: (context, controller) => Text(
              "Hier siehst du dein aktuelles Wort.",
              style: theme.textTheme.bodyMedium?.copyWith(
                color: Colors.white,
              ),
              ),
          ),
        ],
      ),
```

**My environment:**
Flutter version: 3.38.3
Tools • Dart 3.10.1 • DevTools 2.51.1
Coach_mark_tutorials (latest): 1.3.3

Please advice if this can be fixed by downgrading to an older version. Thank you!

**Videos of the issue on two different Android phones:**
Galaxy S25: https://youtube.com/shorts/sdbLd0SvxUg?feature=share
Huawei P20Pro: https://youtube.com/shorts/CcbbagXPqS4?feature=share

**Comment by kounistou** [comment]
Hi all, from my side this was fixed after running:
`flutter pub outdated`
and fixing all outdated dependencies. Unfortunately, I did not spend the time to hunt down the responsible element. But the issue is confirmed as solved with those two devices after the new release was rolled out.

So from my side, I consider this as solved.

**Comment by Dhipin06** [comment]
Hello Team,

I’d like to reopen this issue, as the focus point flickering is still reproducible.

In addition to the previously reported devices (Galaxy S25 and Huawei P20 Pro), the same flickering behavior is also observed on the following device:

Device: Vivo X200  FE (Android)

Environment (unchanged):

Flutter: 3.38.3

Dart: 3.10.1

DevTools: 2.51.1

coach_mark_tutorials: 1.3.3

Kindly please resolve this issue or provide any suggestions or workarounds to fix it.

**Comment by kounistou** [comment]
Hi, @Dhipin06 sorry for the delay. I have reopened the issue. From my side, I do not have further reports about the flickering.

**Comment by sandeepkambham08** [comment]
I see the same flickering issue.
Device: Samsung M13
Android 14

**Comment by RafaelBarbosatec** [comment]
Hi guys!
I will investigate it. But it look be a flutter version problem.
